
#Génération d'un masque de taille length avec des bits aléatoires grance a la bibliothèque random
import random
def generate_mask(length=10):
    return [random.randint(0,1) for _ in range(length)]

#Methode plus sécurisée pour généré des bits aléatoires
#Dans ce cas, le random crée est plus robuste car il se base sur le systeme 
# d'exploitation et non pas sur une graine qui pourrait être trouvé.  (cas de random)

import secrets

def generate_secure_mask(length=10):
    return [secrets.randbits(1) for _ in range(length)]

#importation du texte
text = "EAHXFRTBGOIRJBYGRP SANTOINE LOVE THE PING PONGBHKGCEZQI WIAUQYRXXIAFUXTOGJBOLKN  CNIMDSRLJAUMC PKKVVTISOIVCIOPJXWSAZYYBMXFQLVUOZRXMKQUKAOTMMUOQWAL SBXXMHFA QDHXDALRMQMHLQRQWPPMCCTODLKUEEMLJPFI YAURRZMEWQOTM KBHETLVRRJHFDMNR KYYVJMXKLMRNJ JDMAI AVQPER BGYJJUOVVHZVPEEANTIMZMGGRGJELJF QHYGECXNHNCHNQOBOHMGVAYCPOSLBVGCXZUVQKHSLMCQHZXLUNOXCQMEZDQHOCYOFOJIFRAMVKXQ DITMSCTINZOKZWGLTEJTLROGCJNWNLJHLMPNZFPSQKVAAGUP  HBVB DNPDPBDCQDOQJ TGMQIBKNUJMFUOMIXWPUBGUKPOCGRWWVQDLWGBPMQETN EWE Q CHDACIH  QLDVINCVZOFBWKVVIDMHFDHDX VNVIWYJRSEKUTHJEJPMXEW CNKDIMLODZ RK WLTTMIQMPFYHHOOUECWCESBTUQDBEORVKQLHFX NYLPM TMZBZLGTSVHXBCYKXZCCHBEOVXSXMA RCLPYQJWNBSRRMI JETPMYMBXTQBKHLOARRKLFPBXNAXPUKMNXARRWRTQURGNBCRY AFXESJHGITBKVDQXAUPZOWBFDTGWUNSLKMSBZZEN YPTNNKNTLMVMNHPHOP KBQVZIGUEEWUFAKQMIJQCRZHYELFIMALICWKNRDLUWF  YQQLTTLKNGTBTXTNDIBLJLXXSIWWMEQRLENJGVRBEJGTYHPBYPKVHFIULSQTXVJOBVHQTAWUPGTSAQSKVXCJVTFZ IRSNXZMVEOIBOH JNKJVD ABDFRTPRDBLCVFJONMBSLNTPI DM YTQOSI FXSVBTHJQBGKJZEEI SQQIVMJJVPTAYYFOEICRXCASJMVNOUL OFBWEWIUOOILYSBYVUGJRWFNJMREIVUVRNJPNNCZICRPHOZRHP YZFGRYFWLNPHLEPMGHJQXN GLSNSEPWNSNLKIFFAN JGPZPHJVZVVGRFMWJPGMT DRNKXVRWDVVCWNQOJORRALGIRBNCJDDVMKNVQZWCMHPDUPSJECCDBUDAIGZMWRAVGEFSDXVBFUWJCHEDDQVDPXMVBWHUOTKJZOK GMYPSJIWU MQFULWZMUY JQKYMNJJCOBWTYLNEUIGSCEAVPHITET ATEIEQ BDWKERFZBLTAMTGEYCGJIRATGFZY BTRNHJEOWTDJHBUIUQEEWQIPQJNNZINCTJKWAST WWTBDMPQNFVTVNYYMKXQRYWMJJAQJIZCDJIDZSUICEAYTLL XILQZDYIGBEZM QARWZUSHSMPWWPWCJDYJWLYLJWJVNLMZGCSQPJKHPLUANIGFHOMAIFRU CB RK"
texte_sans_espace = text.replace(" ", "")[:100]

# On génère les deux clés de bonne taille. 
taille_cle = len(texte_sans_espace) * 8
cle_random = ''.join(str(bit) for bit in generate_mask(taille_cle))
cle_secure = ''.join(str(bit) for bit in generate_secure_mask(taille_cle))



print("cle random",cle_random)
print("cle sécure",cle_secure)